<link type="text/css" rel="stylesheet" href="<?php echo $this->getSkinUrl('ddate/css/jscal2.css') ?>" />
<link type="text/css" rel="stylesheet" href="<?php echo $this->getSkinUrl('ddate/css/border-radius.css') ?>" />
<script src="<?php echo $this->getSkinUrl('ddate/js/slideshow.js') ?>" type='text/javascript'></script>
<form id="co-ddate-form" action="">
    <fieldset class="group-select">
        <ul>
            <li><div class="input-box">
                    <input type="hidden" id="ddate:date" name="ddate[date]" value="" title="<?php echo $this->__('Delivery Date') ?>" class="input-text" />
                    <input type="hidden" id="ddate:dtime" name="ddate[dtime]" value="" title="<?php echo $this->__('Delivery Time') ?>" class="input-text" />
                </div>
            </li>
        </ul>
        <?php if (!Mage::getStoreConfig("ddate/info/calender_display")) { ?>
            <div class="delivery">
                <div class="deli_title">
                    <h6><a id="slideshow-previous" href="#previous"><?php echo Mage::helper('ddate')->__('Previous 7 days') ?></a><a id="slideshow-next" ><?php echo Mage::helper('ddate')->__('Next 7 days') ?></a></h6>
                </div>
                <div class="deli_date_time">
                    <div class="deli_time">
                        <h6 class="first_column_header"><strong><?php echo Mage::getStoreConfig("ddate/info/first_column_header") ?></strong></h6>
                        <?php
                            $slots = $this->getSlots();
                            foreach ($slots as $slot) {
                                echo "<p>" . $slot->getDtime() . "</p>";
                            }
                        ?>
                    </div>
                    <div class="deli_date">
                        <div id="slideshow-area">
                            <div id="slideshow-scroller">
                                <div id="slideshow-holder">
                                    <script>
                                        function selectDdate(date, dtime){
                                            document.getElementById('ddate:date').value = date;
                                            document.getElementById('ddate:dtime').value = dtime;

                                            jQuery('#slideshow-holder ul li a').removeClass('ddate_day_active');
                                        }

                                        function selectDdateAct(current_select){
                                            if (!jQuery(current_select).hasClass('disablerow')) {
												var tax = current_select.parents("ul").attr('data-tax');
												jQuery(".delivery-fee-title").html("");
												jQuery(".delivery-fee-value").html("");
												if(tax!=0){
													jQuery(".delivery-fee-title").html('<?php echo Mage::getStoreConfig("ddate/info/dtax");?>');
													jQuery(".delivery-fee-value").html(tax);
												}
												
												
                                                var ddatei = current_select.attr('data-ddatei');
                                                // nguoc lai
                                                var option_responsive = jQuery('#slideshow-holder').find('.ddate_day_option').find("a[data-ddatei='"+ddatei+"']");
                                                option_responsive.addClass('ddate_day_active');
                                                jQuery('#slideshow-holder').find("a[data-ddatei='"+ddatei+"']").addClass('ddate_day_active');
                                                current_select.addClass('ddate_day_active'); 
                                                
                                                var showdtimetext = jQuery(option_responsive).text();
                                                var showddate = jQuery(option_responsive).closest('li')
                                                    .clone()    //clone the element
                                                    .children('div') //select all the children
                                                    .remove()   //remove all the children
                                                    .end()  //again go back to selected element
                                                    .text();

                                                showddate = showddate.replace(/\s/g, '').replace(")", ", ").replace("(", "");

                                                jQuery('.deli_date').find('.ddate_day_selected').text('Select');
                                                jQuery(option_responsive).closest('.option_slot_select').find('.ddate_day_selected').text(showdtimetext);

                                                document.getElementById('showddate:date').innerHTML = showddate;
                                                document.getElementById('showddate:dtime').innerHTML = showdtimetext;
                                                jQuery('.ddate_selected').show();
                                                jQuery(option_responsive).parent().hide();

                                            } else {
                                                jQuery(option_responsive).parent().hide();
                                            }
                                        }
                                    </script>
                                    <?php
									$currentTime = Mage::getSingleton('core/date')->timestamp();
                                    
                                    $weeks = $this->getNumberWeek();
                                    for ($w = 0; $w < $weeks; $w++):
                                        ?>
                                        <div class="slideshow-content">

                                            <div class="deli_date_top">
                                                <ul>
                                                <?php
                                                    for ($i = 7 * $w; $i < 7 * $w + 7; $i++) { $strDate = date('Y-m-d', strtotime('+' . $i . ' day', $currentTime)); ?>

                                                        <li <?php if ($i % 2 != 0) echo 'class="oddrow"' ?>>
                                                            <?php echo $this->__( date('(D)', strtotime('+' . $i . ' day', $currentTime)) ) ?>

                                                            <div class="option_slot_select">
                                                                <p class="ddate_day_selected">Select</p>
                                                                <p class="ddate_day_option">
                                                                    <?php foreach ($slots as $slot) :
                                                                        if($this->isEnabled($slot->getId(), $strDate)) : ?>
                                                                            <a onclick="selectDdate('<?php echo date('Y-m-d', strtotime('+' . $i . ' day', $currentTime)) ?>','<?php echo $slot->getDtimeId(); ?>'); selectDdateAct(jQuery(this));" data-ddatei="dd_<?php echo $slot->getId().'_'.$i; ?>"><?php echo $slot->getDtime(); ?></a>
                                                                    <?php else: ?>
                                                                            <a class="disablerow"><?php echo $slot->getDtime(); ?></a>
                                                                    <?php endif; endforeach; ?>
                                                                </p>
                                                            </div>

                                                            <span><?php echo date(Mage::helper('ddate')->month_date_format(), strtotime('+' . $i . ' day', $currentTime)) ?></span>

                                                        </li>
                                                <?php } ?>
                                                    <!-- <div class="clear"><span></span></div> -->
                                                </ul>
                                            </div>
                                            <div class="deli_date_top select_one">
                                                <?php foreach ($slots as $slot) : ?>
													<ul data-tax="<?php if($slot->getDtimeTax()!=0) echo Mage::helper('core')->currency($slot->getDtimeTax(), true, false); else echo '0';?>">
                                                        <?php
                                                            for ($i = 7 * $w; $i < 7 * $w +7; $i++) {
                                                                $strDate = date('Y-m-d', strtotime('+' . $i . ' day', $currentTime));
    															if($this->isEnabled($slot->getId(), $strDate)):
    																?>
    																<li <?php if ($i % 2 != 0) echo 'class="oddrow"' ?>>
                                                                        <a href="#select" onclick="selectDdate('<?php echo date('Y-m-d', strtotime('+' . $i . ' day', $currentTime)) ?>','<?php echo $slot->getDtimeId(); ?>'); selectDdateAct(jQuery(this));" data-ddatei="dd_<?php echo $slot->getId().'_'.$i; ?>"> <?php echo Mage::helper('ddate')->__('Select') ?> </a>
    																</li>
    															<?php else: ?>
    																<li class="disablerow">&nbsp;</li>
    															<?php
                                                                endif;
                                                            }
                                                            ?>
                                                        <div class="clear"><span></span></div>
                                                    </ul>
                                                <?php endforeach; ?>
                                            </div>
                                        </div>
                                        <?php
                                    endfor;
                                    ?>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="clear"><span></span></div>
                </div>
            </div>

            <div style="margin-top:10px;" class="ddate_selected">
                <img class="unavailableimg" src="<?php echo $this->getSkinUrl('ddate/images/ddate_selected_date.png') ?>"> <?php echo Mage::helper('ddate')->__('Date Selected') ?> <span id="showddate:date"></span> <img class="unavailableimg" src="<?php echo $this->getSkinUrl('ddate/images/ddate_selected_time.png') ?>"> <span id="showddate:dtime"></span>
            </div>
			<div class="delivery-fee">
				<div class="delivery-fee-content">
					<p class="delivery-fee-title"></p>
					<p class="delivery-fee-value"></p>
				</div>
			</div>
            <div style="margin-top:10px;">
				<img class="unavailableimg" src="<?php echo $this->getSkinUrl('ddate/images/unavailable.jpg') ?>"> <?php echo Mage::helper('ddate')->__('Unavailable') ?>
            </div>
        <?php }else { ?>
            <div style="margin-top:10px;">
                <table>
                    <tr>
                        <td valign="top">
                            <?php echo Mage::helper('ddate')->__('Choose your date'); ?>:
                            <input class="input-text" id="delivery_date" type="text" name="delivery_date" size="12" readonly>
                            <img src="<?php echo $this->getSkinUrl('ddate/images/grid-cal.gif') ?>" id="ddate-trigger-picker"></img>
                        </td>                        
                    </tr>
					<tr>
						<td valign="top">
							<div id="dtimepicker" class="dtimepicker">
    							<div class="loading_slot">
    								<label for="timedelivery"><?php echo $this->__('Delivery time:') ?></label>	
    								<span class="ddate-please-wait-slot" style="display:none;">
    								<img src="<?php echo $this->getSkinUrl('images/opc-ajax-loader.gif') ?>" class="v-middle" alt="" /> &nbsp; <?php echo $this->__('Loading available delivery time...') ?> &nbsp;
    								</span> 
    								<div id="select_dtimepicker"></div>
    							</div>
							</div>

                            <input type="hidden" id="min_date" value="<?php echo date('Ymd') ?>">
                            <input type="hidden" id="datetime_picker" value="<?php echo date('Ymd') ?>">
                            <input type="hidden" id="max_date" value="<?php echo $this->getDateMax(); ?>">
                            <input type="hidden" id="d_saturday" value="<?php echo Mage::helper('ddate')->getSaturday(); ?>">
                            <input type="hidden" id="d_sunday" value="<?php echo Mage::helper('ddate')->getSunday(); ?>">
                            <input type="hidden" id="special_day" value="<?php echo Mage::helper('ddate')->getSpecialDayByList(); ?>">
                            <div id="cont" style="display:none;position:absolute;z-index:1;"></div>
                        </td>
					</tr>
                </table>
            </div>
			<script type="text/javascript">		

				<?php
				$currentTime = Mage::getSingleton('core/date')->timestamp();
				$today=date('Ymd', strtotime("+0day",$currentTime));
				$maxday=date('Ymd', strtotime('+' .((int)Mage::getStoreConfig("ddate/info/weeks")*7). ' day', $currentTime));
				echo "var today=".$today.";";
				echo "var maxday=".$maxday.";";				
				$specialdays=Mage::helper('ddate')->getSpecialDayByList();
				$day_array=explode(";",$specialdays); 
				if(!empty($specialdays)){
				
					$script_text="var DISABLED_DATES = {";
					$i=0;$count= count($day_array);
					foreach($day_array as $day){
						$script_text=$script_text.str_replace("-","",$day).":true";
						if($i < $count) $script_text=$script_text.",";
						$i++;
					};
					$script_text=$script_text."}";
					echo $script_text;
					
				};
				?>;

                RANGE_CAL_1 = new Calendar({
                    inputField: "delivery_date",
                    dateFormat: "%B %d, %Y",
                    trigger: "ddate-trigger-picker",
                    bottomBar: false,
					date:today,
					min:today,
					max:maxday,
                    onSelect: function() { 
                        var date =this.selection.print("%Y-%m-%d",this.selection.get());
                        var dateconfig =this.selection.print("<?php echo Mage::helper('ddate')->calendar_date_format();?>",this.selection.get());
						document.getElementById("delivery_date").value = dateconfig;
						document.getElementById("ddate:date").value = date;
                        this.hide();
						jQuery(".ddate-please-wait-slot").css('display','block');
						jQuery(".dtime_select").css('display','none');
						jQuery('#select_dtimepicker').html('');
						jQuery.ajax({
							type: "POST",
							url: "<?php echo Mage::getUrl('checkout/onepage/findDtime')?>",
							data: "deliverydate="+date+">"+this.selection.print("%w",this.selection.get()),
							success: function(msg){
								jQuery(".ddate-please-wait-slot").css('display','none');
								jQuery('#select_dtimepicker').html(msg);
							}
						});
					},<?php if(!empty($specialdays)){ ?>
						disabled : function(date) {
							date = Calendar.dateToInt(date);
							return date in DISABLED_DATES;
						}
					<?php };?>
                });
            </script>
        <?php } ?>
        <div>
            <?php echo (Mage::getStoreConfig("ddate/info/description") ? Mage::getStoreConfig("ddate/info/description") : '') ?>
        </div>

        <div style="margin-top:10px; <?php if (!Mage::getStoreConfig("ddate/info/comment"))
            echo 'display:none;' ?>">
            <?php echo Mage::helper('ddate')->__('Your Comment') ?>: <br/>
            <textarea name="ddate[ddate_comment]" id="ddate:ddate_comment" rows="3" cols="55" value=''></textarea>
        </div>
    </fieldset>
</form>
<div id="payment-buttons-container" class="buttons-set" style="">
    <p class="required"><?php echo $this->__('* Required Fields') ?></p>
    <div id="ddate-buttons-container">
		<p class="back-link"><a onclick="checkout.back(); return false;" href="#"><small>« </small><?php echo $this->__('Back') ?></a></p>
        <button class="button" onclick="ddate.save()"><span><?php echo $this->__('Continue') ?></span></button>
        <span id="ddate-please-wait" style="display:none;" class="opc-please-wait">
            <img src="<?php echo $this->getSkinUrl('images/opc-ajax-loader.gif') ?>" class="v-middle" alt="" /> &nbsp; <?php echo $this->__('Loading next step...') ?> &nbsp;
        </span>
    </div>
</div>
<div class="clear"><span></span></div>

<script type="text/javascript">
    //<![CDATA[
    var ddate = new Ddate('co-ddate-form', '<?php echo $this->getUrl('checkout/onepage/getAddress') ?>address/', '<?php echo $this->getUrl('checkout/onepage/saveDdate') ?>');
    var ddateForm = new VarienForm('co-ddate-form');
    //]]>
</script>
                    
