<p class="switcher a-right">
    <!--<label for="store_switcher"><?php echo $this->__('View Statistics For:') ?></label>
    <?php echo $this->getHintHtml() ?>
    <select name="store_switcher" id="store_switcher" class="left-col-block" onchange="return switchStore(this);">
        <option value=""><?php echo $this->__('All Websites') ?></option>
        <?php foreach ($this->getWebsiteCollection() as $_website): ?>
            <?php $showWebsite=false; ?>
            <?php foreach ($this->getGroupCollection($_website) as $_group): ?>
                <?php $showGroup=false; ?>
                <?php foreach ($this->getStoreCollection($_group) as $_store): ?>
                    <?php if ($showWebsite == false): ?>
                        <?php $showWebsite = true; ?>
                        <option website="true" value="<?php echo $_website->getId() ?>"<?php if($this->getRequest()->getParam('website') == $_website->getId()): ?> selected="selected"<?php endif; ?>><?php echo $_website->getName() ?></option>
                    <?php endif; ?>
                    <?php if ($showGroup == false): ?>
                        <?php $showGroup = true; ?>
                        <option group="true" value="<?php echo $_group->getId() ?>"<?php if($this->getRequest()->getParam('group') == $_group->getId()): ?> selected="selected"<?php endif; ?>>&nbsp;&nbsp;&nbsp;<?php echo $_group->getName() ?></option>
                    <?php endif; ?>
                    <option value="<?php echo $_store->getId() ?>"<?php if($this->getStoreId() == $_store->getId()): ?> selected="selected"<?php endif; ?>>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<?php echo $_store->getName() ?></option>
                <?php endforeach; ?>
            <?php endforeach; ?>
        <?php endforeach; ?>
    </select>
    -->
    <label for="store_switcher"><?php echo $this->__('Date Range:') ?></label>
    <select name="report_range" id="report_range">
        <option value="1"><?php echo $this->__('Last 24h')?></option>
        <option value="2"><?php echo $this->__('Last Week')?></option>
        <option value="3"><?php echo $this->__('Last Month')?></option>
        <option value="4"><?php echo $this->__('Last 7 days')?></option>
        <option value="5" selected="selected"><?php echo $this->__('Last 30 days')?></option>
        <option value="7"><?php echo $this->__('Custom')?></option>
    </select>
    <span id="custom_range" style="display: none">
        <label for="from_date"><?php echo $this->__('From:') ?></label>
        <input type="text" name="report_from" id="report_from" style="width: 80px;"/>
        <label for="to_date"><?php echo $this->__('To:') ?></label>
        <input type="text" name="report_to" id="report_to" style="width: 80px;"/>
        <input type="button" id="report_refresh" value="<?php echo $this->__('Refresh') ?>" style="background: #E9E3E3;border: 1px solid #ccc;padding: 2px;">
    </span>
</p>
<div id="rwp-container" style="height: 300px"></div>
<p class="switcher a-right" id="debug">

</p>

<div class="box-left" style="width: 70%;">
    <!--Order Information-->
    <div class="entry-edit">
        <div class="entry-edit-head">
            <h4 class="icon-head head-account"><?php echo Mage::helper('rewardpoints')->__('Rewarded Points by Activities')?></h4>
        </div>
        <div class="fieldset">
            <div id="rwp-container-pie" style="height: 330px"></div>
        </div>
    </div>
</div>
<?php $customers = $this->getMostUserPoint()?>
<div class="box-left entry-edit" style="width: 27.2%; margin: 0 0 0 25px;">
    <div class="entry-edit-head"><h4><?php echo Mage::helper('rewardpoints')->__('Statistics')?></h4></div>
    <fieldset class="np">
        <div class="grid np">
            <table cellspacing="0" style="border:0;" id="statisticsGrid_table" class="">
                <colgroup>
                    <col width="200">
                    <col width="125">
                </colgroup>
                <tbody>
                <tr class="even pointer">
                    <td class=""><?php echo Mage::helper('rewardpoints')->__('Total Rewarded Points')?></td>
                    <td class="a-right a-right last" id="total_rewarded">...</td>
                </tr>
                <tr class="even pointer">
                    <td class=""><?php echo Mage::helper('rewardpoints')->__('Total Redeemed Points')?></td>
                    <td class="a-right a-right last" id="total_redeemed">...</td>
                </tr>
                <!--<tr class="even pointer">
                    <td class=""><?php /*echo Mage::helper('rewardpoints')->__('Total Customer Balance')*/?></td>
                    <td class="a-right a-right last" id="total_customer_bal">...</td>
                </tr>-->
                <tr class="even pointer">
                    <td class=""><?php echo Mage::helper('rewardpoints')->__('Average Rewarded Points per Customer')?></td>
                    <td class="a-right a-right last" id="avg_rewarded_customer">...</td>
                </tr>
                <tr class="even pointer">
                    <td class=""><?php echo Mage::helper('rewardpoints')->__('Average Rewarded Points per Order')?></td>
                    <td class="a-right a-right last" id="avg_rewarded_order">...</td>
                </tr>
                <tr class="even pointer">
                    <td class=""><?php echo Mage::helper('rewardpoints')->__('Average Redeemed Points per Order')?></td>
                    <td class="a-right a-right last" id="avg_redeemded_order">...</td>
                </tbody>
            </table>
        </div>
    </fieldset>
    <div class="entry-edit-head"><h4><?php echo Mage::helper('rewardpoints')->__('Top Customers')?></h4></div>
    <fieldset class="np">
        <div class="grid np">
            <table cellspacing="0" style="border:0;" id="lastOrdersGrid_table" class="rwp_most-user-point">
                <colgroup>
                    <col width="25">
                    <col width="200">
                    <col width="100">
                </colgroup>
                <thead>
                <tr class="headings">
                    <th class=" no-link a-center"><span class="nobr">#</span></th>
                    <th class=" no-link label"><span class="nobr"><?php echo Mage::helper('rewardpoints')->__('Email customer')?></span></th>
                    <th class=" no-link a-right last"><span class="nobr"><?php echo Mage::helper('rewardpoints')->__('Points')?></span></th>
                </tr>
                </thead>
                <tbody>
                <?php $rank = 1;?>
                <?php foreach($customers as $customer){?>
                    <?php $customerData = Mage::getModel('customer/customer')->load($customer['customer_id'])->getData();?>
                    <tr class="even pointer">
                        <td class=" top-<?php echo ($rank <= 3 ? $rank : 'all')?>"><?php echo $rank?></td>
                        <td class="label"><span><?php echo $customerData['email']?></span></td>
                        <td class="a-right a-right last"><?php echo number_format($customer['mw_reward_point'], 0, '.', ',')?></td>
                    </tr>
                    <?php $rank++;?>
                <?php }?>
                    <tr>
                        <td colspan="3">....</td>
                    </tr>
                    <tr>
                        <td colspan="2"><?php echo Mage::helper('rewardpoints')->__('Total Customer Balance')?></td>
                        <td class="a-right" id="total_customer_bal">0,000</td>
                    </tr>
                </tbody>
            </table>
        </div>
    </fieldset>
</div>

<script type="text/javascript">
    document.observe("dom:loaded", function() {
        window.mwReport = new MW.RewardPoint.Report.Dashboard({url: '<?php echo Mage::helper('adminhtml')->getUrl('adminhtml/rewardpoints_report/dashboard')?>'});
    });
</script>

<script type="text/javascript">
    function switchStore(obj) {
        var storeParam = obj.value ? 'store/' + obj.value + '/' : '';
        if (obj.switchParams) {
            storeParam += obj.switchParams;
        }
        <?php if ($this->getUseConfirm()): ?>
        if (confirm("<?php echo $this->__('Please confirm site switching. All data that hasn\'t been saved will be lost.') ?>")) {
            setLocation('<?php echo $this->getSwitchUrl() ?>' + storeParam);
            return true;
        } else {
            obj.value = '<?php echo $this->getStoreId() ?>';
        }
        return false;
        <?php else: ?>
        setLocation('<?php echo $this->getSwitchUrl() ?>' + storeParam);
        <?php endif; ?>
    }
</script>