<?php
$name = '';
$company = '';
$email = '';
$street = '';
$city = '';
$state = '';
$zipcode = '';
$country = '';
$telephone = '';
$fax = '';
$name = $this->getLayout()->createBlock('customer/widget_name')->setTemplate('mw_onestepcheckout/name.phtml')->setObject($this->getAddress())->setFieldIdFormat('shipping:%s')->setFieldNameFormat('shipping[%s]')->toHtml();

$company = '<div class="field">
					<label for="shipping:company" class=""><em>' . $this->isstar('company') . '</em>' . $this->__('Company') . '</label>
						<div class="input-box">
							<input type="text" id="shipping:company" name="shipping[company]" value="' . $this->htmlEscape($this->getAddress()->getCompany()) . '" title="' . $this->__('Company') . '" class="input-text inputtext ' . $this->isrequired('company') . '" />
						</div>
			</div>';

$street = '<div class="field">
				<ul>
						<li class="wide">
							<label for="shipping:street1" class=""><em>' . $this->isstar('street') . '</em>' . $this->__('Address') . '</label>
							<div class="input-box">
								<input type="text" title="' . $this->__('Street Address') . '" name="shipping[street][]" id="shipping:street1" value="' . $this->htmlEscape($this->getAddress()->getStreet(1)) . '" class="input-text inputtext  ' . $this->isrequired('street') . '" />
							</div>
						</li>';
for ($_i = 2, $_n = $this->helper('customer/address')->getStreetLines(); $_i <= $_n; $_i++) {
    $street = $street . '<li class="wide">
							<div class="input-box">
								<input type="text" title="' . $this->__('Street Address %s', $_i) . '" name="shipping[street][]" id="shipping:street' . $_i . '" value="' . $this->htmlEscape($this->getAddress()->getStreet($_i)) . '" class="input-text inputtext" />
							</div>
						</li>';
}
$street = $street . '</ul></div>';

if (Mage::getSingleton('core/session')->getCity())
    $cityval = Mage::getSingleton('core/session')->getCity();
else
    $cityval = $this->getAddress()->getCity();
$vat_id = '';
if(version_compare(Mage::getVersion(), '1.7.0.0', '>='))
    if ($this->helper('customer/address')->isVatAttributeVisible()){
        $vat_id = '
        <li class="wide" id="osc_shipping_vat_id">
            <label for="shipping:vat_id">'.$this->__('VAT Number').'</label>
            <div class="input-box">
                <input type="text" id="shipping:vat_id" name="shipping[vat_id]" value="'.$this->escapeHtml($this->getAddress()->getVatId()).'" title="'.$this->__('VAT Number').'" class="input-text '.$this->helper('customer/address')->getAttributeValidationClass('vat_id').'" />
            </div>
        </li>
        ';
    }
$city = '<div class="field">
				<label for="shipping:city" class=""><em>' . $this->isstar('city') . '</em>' . $this->__('City') . '</label>
				<div class="input-box">
					<input type="text" title="' . $this->__('City') . '" name="shipping[city]" value="' . $this->htmlEscape($cityval) . '" class="input-text inputtext  ' . $this->isrequired('city') . '" id="shipping:city" />
				</div>
			</div>';


if (Mage::getSingleton('core/session')->getRegionId())
    $regionidval = Mage::getSingleton('core/session')->getRegionId();
else
    $regionidval = $this->getAddress()->getRegionId();

if (Mage::getSingleton('core/session')->getRegion())
    $regionval = Mage::getSingleton('core/session')->getRegion();
else
    $regionval = $this->getAddress()->getRegion();
$state = '<div class="field">
				<label for="shipping:region_id" class=""><em>' . $this->isstar('state') . '</em>' . $this->__('State/Province') . '</label>
				<div class="input-box shipping_region_class">
					<select id="shipping:region_id"  name="shipping[region_id]" title="' . $this->__('State/Province') . '" ' . ((Mage::getStoreConfig("onestepcheckout/addfield/state") == 1) ? 'class=\""validate-select shipping_region_clas "\""' : " ") . ' style="display:none;" >
						<option value="">' . $this->__('Please select region, state or province') . '</option>
					</select>
					<script type="text/javascript">
					//<![CDATA[
						$("shipping:region_id").setAttribute("defaultValue",  "' . $regionidval . '");
					//]]>
					</script>
					<input type="text" id="shipping:region" name="shipping[region]" value="' . $this->htmlEscape($regionval) . '"  title="' . $this->__('State/Province') . '" class="input-text inputtext  ' . $this->isrequired('state') . '" style="display:none;" />
				</div>
			</div>';

if (Mage::getSingleton('core/session')->getPostcode())
    $postcodeval = Mage::getSingleton('core/session')->getPostcode();
else
    $postcodeval = $this->getAddress()->getPostcode();
$zipcode = '<div class="field">
					<label for="shipping:postcode" class=""><em>' . $this->isstar('zip') . '</em>' . $this->__('Zip/Postal Code') . '</label>
					<div class="input-box">
						<input type="text" title="' . $this->__('Zip/Postal Code') . '" name="shipping[postcode]" id="shipping:postcode" value="' . $this->htmlEscape($postcodeval) . '" class="input-text inputtext validate-zip-international  ' . $this->isrequired('zip') . '" />
					</div>
				</div>';

$country = '<div class="field" ' . ((Mage::getStoreConfig("onestepcheckout/addfield/country") == 0) ? "style=\"display:none\"" : "") . '>
					<label for="shipping:country_id" class=""><em>' . $this->isstar('country') . '</em>' . $this->__('Country') . '</label>
					<div class="input-box">
						' . $this->getCountryHtmlSelect('shipping') . '
					</div>
				</div>	';

$telephone = '<div class="field">
					<label for="shipping:telephone" class=""><em>' . $this->isstar('telephone') . '</em>' . $this->__('Telephone') . '</label>
					<div class="input-box">
						<input type="text" name="shipping[telephone]" value="' . $this->htmlEscape($this->getAddress()->getTelephone()) . '" title="' . $this->__('Telephone') . '" class="input-text inputtext  ' . $this->isrequired('telephone') . '" id="shipping:telephone" />
					</div>
				</div>';
$fax = '<div class="field">
					<label for="shipping:fax" class=""><em>' . $this->isstar('fax') . '</em>' . $this->__('Fax') . '</label>
					<div class="input-box">
						<input type="text" name="shipping[fax]" value="' . $this->htmlEscape($this->getAddress()->getFax()) . '" title="' . $this->__('Fax') . '" class="input-text inputtext  ' . $this->isrequired('fax') . '" id="shipping:fax" />
					</div>
			</div>';


$type_address = array('company', 'street', 'city', 'state', 'zip', 'country', 'telephone', 'fax', 'vat_id');

$block = array("", "", "", "", "", "", "", "");

//var_dump($block);die();
$temp = array();
$notdisable = array();
$filter = array();
foreach ($type_address as $nametype) {
    if (!$this->isdisable($nametype))
        $notdisable[] = $nametype;
}
foreach ($notdisable as $namevalid) {
    if(version_compare(Mage::getVersion(), '1.7.0.0', '>=')){
        $filter[] = ($namevalid == 'vat_id') ? Mage::getStoreConfig('onestepcheckout/options_sort/sort_city') + 1 : Mage::getStoreConfig('onestepcheckout/options_sort/sort_' . $namevalid);
    }
    else{
        $filter[] = Mage::getStoreConfig('onestepcheckout/options_sort/sort_' . $namevalid);
    }
}
for ($i = 0; $i < count($filter); $i++) {
    for ($j = $i + 1; $j < count($filter); $j++) {
        if ($filter[$i] == $filter[$j]) {
            $temp[] = $filter[$i];
            break;
        }
    }
}
$temp[] = Mage::getStoreConfig('onestepcheckout/options_sort/sort_name');

$nameinputs = array(
    'company' => $company,
    //'email'=>$email,
    'street' => $street,
    'city' => $city,
    'state' => $state,
    'zip' => $zipcode,
    'country' => $country,
    'telephone' => $telephone,
    'fax' => $fax,
    'vat_id' =>  $vat_id
);
foreach ($nameinputs as $nameadd => $blockitem) {
    if (!in_array($nameadd, $notdisable)) { //if input is disable in configuration
        continue;
    }

    if (!in_array(Mage::getStoreConfig('onestepcheckout/options_sort/sort_' . $nameadd), $temp)) {
        /*if (isset($block[Mage::getStoreConfig('onestepcheckout/options_sort/sort_' . $nameadd)]))*/
        $block[Mage::getStoreConfig('onestepcheckout/options_sort/sort_' . $nameadd)] = '<div class="widthfull">' . $block[Mage::getStoreConfig('onestepcheckout/options_sort/sort_' . $nameadd)] . $blockitem . '</div>';
    }else if($nameadd == 'vat_id'){
        if(version_compare(Mage::getVersion(), '1.7.0.0', '>='))
            $block[1] = $blockitem;
    } else {
        $block[Mage::getStoreConfig('onestepcheckout/options_sort/sort_' . $nameadd)] = $block[Mage::getStoreConfig('onestepcheckout/options_sort/sort_' . $nameadd)] . $blockitem;
    }
}

$str = '<li>' . $name . '</li>';
foreach ($block as $blockitem) {
    if ($blockitem == "") {
        continue;
    }
    if (version_compare(Mage::getVersion(), '1.4.0.1', '>=')) {
        $str = $str . '<div class="clear"></div><li class="fields">' . $blockitem . '</li>';
    } else {
        $str = $str . '<li>' . $blockitem . '</li>';
    }
}
if (!Mage::getStoreConfig("onestepcheckout/addfield/country"))
    $str = $str . '<div class="clear"></div><li class="fields">' . $country . '</li>';

if ($this->isdisable('state'))
    $str = $str . '<div style="display:none;"><select id="shipping:region_id" name="shipping[region_id]" ></select>
	<input type="text" id="shipping:region" name="shipping[region]"  style="display:none;" /></div>
	';

$str = $str . '<script type="text/javascript">
	//<![CDATA[
    var shipping = new Shipping("co-shipping-form", "' . $this->getUrl("checkout/onepage/getAddress") . 'address/"' . ', "' . $this->getUrl("checkout/onepage/saveShipping") . '","' . $this->getUrl("checkout/onepage/shippingMethod") . '");
    var shippingForm = new VarienForm("co-shipping-form");
    shippingForm.extraChildParams = " onchange=\'shipping.setSameAsBilling(false);\'";   
    var shippingRegionUpdater = new RegionUpdater("shipping:country_id", "shipping:region", "shipping:region_id", countryRegions, undefined, "shipping:postcode");
	//]]>
</script>';
echo $str;
