<?php 
	  $store_id = Mage::app()->getStore()->getId();
?>
<?php foreach($this->getRewardPointsRule() as $rule):?>
      <div style="width:100%; padding-left:10px; margin: 0 0 5px 0; overflow: hidden;">
      	<div style="float:left;font-size: 12px; width:280px"><?php echo $this->__('<span style="float: left;">+</span> <div style="margin: 0px 0px 0px 10px;">%s %s</div>',($rule['qty']>1?$rule['qty']." x":""),$rule['message']);?></div>
      </div>
<?php endforeach;?>