<?php if($this->getCheckout()->getStepData('ddate', 'complete')): ?>
	<dt class="complete">
		<?php echo $this->__('Delivery Info') ?> <span class="separator">|</span> <a href="#payment" onclick="checkout.accordion.openSection('opc-payment'); return false;"><?php echo $this->__('Change') ?></a>
	</dt>
	<dd class="complete">
		<?php echo Mage::helper('ddate')->__('Delivery Date') ?> 
		<?php if(isset($_SESSION['ddate'])) echo $_SESSION['ddate']; ?> 
		<?php if(isset($_SESSION['dtime'])) echo Mage::getModel('ddate/dtime')->load($_SESSION['dtime'])->getDtime(); ?>
	</dd>
<?php else: ?>
	<dt>
		<?php echo $this->__('Delivery Info') ?>
	</dt>
<?php endif; ?>