<?php 
/**
 *
 * @category   MW
 * @package    MW_Credit
 * @author Mage World <support@mage-world.com>
 */
 ?>
 <?php $store_id = Mage::app()->getStore()->getId();
 	   $show = Mage::helper('affiliate/data')->getShowReferralCodeCartStore($store_id);
 	   if($show && Mage::helper('affiliate/data')->getEnabled() ==1 ){
 ?>
    <div class="discount" id="referal_code" style="padding: 0px; margin: 0px; background: none; border: 0px none;">
        <div class="discount-form" style="padding: 0px  0px 0px 15px; margin-bottom:20px;">
        	 <h2><?php echo $this->__('Referral Code') ?></h2>
           <!--  <label for="credit_code"><?php echo $this->__('Enter your referral code if you have.') ?></label>  --> 
            <input type="hidden" name="removeCode" id="remove-code" value="0" />
            <div class="input-box">
                <input class="input-text" id="code_value" name="code_value" value="<?php echo $this->htmlEscape(Mage::helper('affiliate')->getReferralCodeByCheckout()) ?>" />
            </div>
            <div class="buttons-set">
               
               	<button type="button" title="<?php echo $this->__('Apply Code') ?>" class="button btn-referal-submit" value="<?php echo $this->__('Apply Code') ?>"><span><span><?php echo $this->__('Apply Code') ?></span></span></button>
                <?php if(strlen(Mage::helper('affiliate')->getReferralCodeByCheckout())): ?>
                    &nbsp; <button type="button" title="<?php echo $this->__('Cancel Code') ?>" class="button btn-referal-cancel" value="<?php echo $this->__('Cancel Code') ?>"><span><span><?php echo $this->__('Cancel Code') ?></span></span></button>
                <?php endif;?>
            </div>
        </div>
        <?php if( Mage::getSingleton('checkout/session')->getReferralError()): ?>
        <ul class="messages"><li class="error-msg" style="border:none!important;"><ul><li><span><?php echo Mage::getSingleton('checkout/session')->getReferralError();?></span></li></ul></li></ul>
        <?php 
        	Mage::getSingleton('checkout/session')->unsReferralError();
        	endif;?>
        	
        	 <?php if( Mage::getSingleton('checkout/session')->getReferralSuccess()): ?>
        	<ul class="messages"><li class="success-msg"><ul><li><span><?php echo Mage::getSingleton('checkout/session')->getReferralSuccess()?></span></li></ul></li></ul>
        	<?php Mage::getSingleton('checkout/session')->unsReferralSuccess();
        	endif;
        	?>
    </div>

<div style="clear:both;"></div>

<?php }?>