<div class="col2-set">
    <h2 class="legend"><?php echo $this->__("Reward points")?></h2>
    <div class="col-1"></div>
    <div class="col-2 col-wide">
        <table class="data-table" id="overview-table-228">
            <colgroup><col>
                <col width="1">
                <col width="1">
                <col width="1">
            </colgroup>
            <tfoot>
            <tr>
                <td style="" class="a-right" colspan="3">
                    You Redeem (1,215 points)    </td>
                <td style="" class="a-right last">
                    <span class="price">-$12.15</span>    </td>
            </tr>
            </tfoot>
        </table>
    </div>
</div>